Polynomial Equalizer: EQCurveView Class Reference
EQCurveView Class Reference
Visualizes the current state of the EQ curve.
#include <eqcurveview.hpp>
Public Member Functions
void draw (VSTGUI::CDrawContext *dc) override
Core rendering method of the view.
EQCurveView (const VSTGUI::CRect &size)
void onParamChanged (Steinberg::Vst::ParamID id, float normalizedValue)
Relays user input to internal states.
void setParamListeners (controller_t controller)
Private Member Functions
float dbToY (float db) const
void drawDbMarkers (VSTGUI::CDrawContext *dc) const
void drawFreqMarkers (VSTGUI::CDrawContext *dc) const
float freqToX (float freq) const
Helper that binds a frequency to the graph's X axis.
Private Attributes
controller_t _controller = nullptr
float _direction = EQ::kDefaultDirection
listener_t _directionListener
float _intensity = EQ::kDefaultIntensity
listener_t _intensityListener
const float _padding = 20.0f
EqShapePreset _shape = EqShape::kDefaultEqShape
listener_t _shapeListener
float _shift = EQ::kDefaultShift
listener_t _shiftListener
float _width = EQ::kDefaultWidth
listener_t _widthListener
Detailed Description
Visualizes the current state of the EQ curve.
Manages the live visualization of the EQ curve and reflects the changes made by altering parameters.
Definition at line 38 of file eqcurveview.hpp.
Constructor & Destructor Documentation
EQCurveView()
EQCurveView::EQCurveView (const VSTGUI::CRect & size) inline explicit
Definition at line 40 of file eqcurveview.hpp.
        : CView(size) { }
Member Function Documentation
dbToY()
float EQCurveView::dbToY (float db) const private
Definition at line 103 of file eqcurveview.cpp.
{
    constexpr float visualMaxDB = EQ::dBMaxBoost + 8.0f;
    const float drawableHeight = getHeight() - 2 * _padding;
    const float normY = (visualMaxDB - db) / (2 * visualMaxDB);
    return _padding + normY * drawableHeight;
}
References _padding, and EQ::dBMaxBoost.
draw()
void EQCurveView::draw (VSTGUI::CDrawContext * dc) override
Core rendering method of the view.
Draws an up-to-date graph of the EQ curve.
Parameters
dc A drawing context abstracting drawing regardless of OS
Definition at line 9 of file eqcurveview.cpp.
{
    dc->setDrawMode(VSTGUI::kAntiAliasing);
    drawFreqMarkers(dc);
    drawDbMarkers(dc);
    dc->setLineWidth(2);
    dc->setFrameColor(VSTGUI::CColor(0, 255, 0, 255));
    const float centerFreq = expf(logf(EQ::minFreq) + _shift * (logf(EQ::maxFreq) - logf(EQ::minFreq)));
    const float flip = 1.0f - 2.0f * _direction;
    const float dBpeakGain = flip * _intensity * EQ::dBMaxBoost;
    const auto path = dc->createGraphicsPath();
    const int numPoints = static_cast<int>(getWidth());
    for (int i = 0; i < numPoints; ++i)
    {
        const float normX = static_cast<float>(i) / numPoints;
        const float logFreq = log10f(EQ::minFreq) + normX * (log10f(EQ::maxFreq) - log10f(EQ::minFreq));
        const float freq = powf(10.0f, logFreq);
        const float x = (freq - centerFreq) / (centerFreq * _width);
        float shape = shapeFromPreset(_shape, x);
        if (shape < 0.0f) shape = 0.0f;
        const float dBgain = dBpeakGain * shape;
        float px = freqToX(freq);
        float py = dbToY(dBgain);
        if (i == 0)
            path->beginSubpath({px, py});
        else
            path->addLine({px, py});
    }
    dc->drawGraphicsPath(path, VSTGUI::CDrawContext::kPathStroked);
    dc->drawGraphicsPath(path, VSTGUI::CDrawContext::kPathStroked);
    path->forget();
}
References _direction, _intensity, _shape, _shift, _width, EQ::dBMaxBoost, dbToY(), drawDbMarkers(), drawFreqMarkers(), freqToX(), EQ::maxFreq, EQ::minFreq, and shapeFromPreset().
drawDbMarkers()
void EQCurveView::drawDbMarkers (VSTGUI::CDrawContext * dc) const private
Definition at line 143 of file eqcurveview.cpp.
{
    static const std::vector<float> dbMarkers = { 18.0f, 12.0f, 6.0f, -6.0f, -12.0f, -18.0f};
    dc->setFont(VSTGUI::kNormalFontVerySmall);
    dc->setFontColor(VSTGUI::CColor(180, 180, 180, 255));
    for (float db : dbMarkers)
    {
        float y = dbToY(db);
        if (y < _padding || y > getHeight() - _padding)
            continue;
        std::string label;
        if (db > 0)
            label = "+" + std::to_string(static_cast<int>(db)) + "dB";
        else
            label = std::to_string(static_cast<int>(db)) + "dB";
        VSTGUI::CRect textRect(3, y - 6, 30, y + 6);
        dc->drawString(label.c_str(), textRect, VSTGUI::kLeftText);
    }
}
References _padding, and dbToY().
drawFreqMarkers()
void EQCurveView::drawFreqMarkers (VSTGUI::CDrawContext * dc) const private
Definition at line 112 of file eqcurveview.cpp.
{
    dc->setLineWidth(1);
    dc->setFrameColor(VSTGUI::CColor(100, 100, 100, 128));
    dc->setFont(VSTGUI::kNormalFontVerySmall);
    dc->setFontColor(VSTGUI::CColor(180, 180, 180, 255));
    static const std::vector<float> freqMarkers = {
        30.0f, 50.0f, 100.0f, 200.0f, 500.0f,
        1000.0f, 2000.0f, 5000.0f, 10000.0f
    };
    for (const float freq : freqMarkers)
    {
        if (freq < EQ::minFreq || freq > EQ::maxFreq)
            continue;
        float x = freqToX(freq);
        dc->drawLine(VSTGUI::CPoint(x, 0), VSTGUI::CPoint(x, getHeight()));
        std::string label;
        if (freq >= 1000.0f)
            label = std::to_string(static_cast<int>(freq / 1000.0f)) + "k";
        else
            label = std::to_string(static_cast<int>(freq));
        VSTGUI::CRect textRect(x - 15, getHeight() - 15, x + 15, getHeight());
        dc->drawString(label.c_str(), textRect, VSTGUI::kCenterText);
    }
}
References freqToX(), and EQ::maxFreq.
freqToX()
float EQCurveView::freqToX (float freq) const private
Helper that binds a frequency to the graph's X axis.
Parameters
freq EQ
Returns
X value on the graph.
Definition at line 97 of file eqcurveview.cpp.
{
    const float normX = (log10f(freq) - log10f(EQ::minFreq))/ (log10f(EQ::maxFreq) - log10f(EQ::minFreq));
    return normX * getWidth();
}
References EQ::maxFreq, and EQ::minFreq.
onParamChanged()
void EQCurveView::onParamChanged (Steinberg::Vst::ParamID id, float normalizedValue)
Relays user input to internal states.
Parameters
id ID of the parameter being handled.
normalizedValue Value to-be updated internally for rendering purposes.
Definition at line 68 of file eqcurveview.cpp.
{
    switch (id)
    {
        case kParamShift:
            _shift = normalizedValue;
        break;
        case kParamWidth:
            _width = normalizedValue;
        break;
        case kParamIntensity:
            _intensity = normalizedValue;
        break;
        case kParamDirection:
            _direction = normalizedValue;
        break;
        case kParamShape:
        {
            int maxShapeIndex = static_cast<int>(EqShapePreset::Count) - 1;
            int shapeIndex = static_cast<int>(normalizedValue * maxShapeIndex + 0.5f);
            shapeIndex = std::clamp(shapeIndex, 0, maxShapeIndex);
            _shape = static_cast<EqShapePreset>(shapeIndex);
            break;
        }
    }
}
References _direction, _intensity, _shape, _shift, _width, Count, kParamDirection, kParamIntensity, kParamShape, kParamShift, and kParamWidth.
setParamListeners()
void EQCurveView::setParamListeners (controller_t controller)
Definition at line 52 of file eqcurveview.cpp.
{
    this->_controller = controller;
    _shiftListener = std::make_unique<CustomParamListener>(
        _controller->getParameterObject(kParamShift), this, _controller);
    _widthListener = std::make_unique<CustomParamListener>(
        _controller->getParameterObject(kParamWidth), this, _controller);
    _intensityListener = std::make_unique<CustomParamListener>(
        _controller->getParameterObject(kParamIntensity), this, _controller);
    _directionListener = std::make_unique<CustomParamListener>(
        _controller->getParameterObject(kParamDirection), this, _controller);
    _shapeListener = std::make_unique<CustomParamListener>(
        _controller->getParameterObject(kParamShape), this, _controller);
}
References _controller, _directionListener, _intensityListener, _shapeListener, _shiftListener, _widthListener, kParamDirection, kParamIntensity, kParamShape, kParamShift, and kParamWidth.
Member Data Documentation
_controller
controller_t EQCurveView::_controller = nullptr private
Definition at line 71 of file eqcurveview.hpp.
_direction
float EQCurveView::_direction = EQ::kDefaultDirection private
Definition at line 82 of file eqcurveview.hpp.
_directionListener
listener_t EQCurveView::_directionListener private
Definition at line 76 of file eqcurveview.hpp.
_intensity
float EQCurveView::_intensity = EQ::kDefaultIntensity private
Definition at line 81 of file eqcurveview.hpp.
_intensityListener
listener_t EQCurveView::_intensityListener private
Definition at line 75 of file eqcurveview.hpp.
_padding
const float EQCurveView::_padding = 20.0f private
Definition at line 85 of file eqcurveview.hpp.
_shape
EqShapePreset EQCurveView::_shape = EqShape::kDefaultEqShape private
Definition at line 83 of file eqcurveview.hpp.
_shapeListener
listener_t EQCurveView::_shapeListener private
Definition at line 77 of file eqcurveview.hpp.
_shift
float EQCurveView::_shift = EQ::kDefaultShift private
Definition at line 79 of file eqcurveview.hpp.
_shiftListener
listener_t EQCurveView::_shiftListener private
Definition at line 73 of file eqcurveview.hpp.
_width
float EQCurveView::_width = EQ::kDefaultWidth private
Definition at line 80 of file eqcurveview.hpp.
_widthListener
listener_t EQCurveView::_widthListener private
Definition at line 74 of file eqcurveview.hpp.
The documentation for this class was generated from the following files:
eqcurveview.hpp
eqcurveview.cpp