Polynomial Equalizer: PluginProcessor Class Reference
PluginProcessor Class Reference
Main class for the audio processing part of the plugin.
#include <processor.hpp>
Public Member Functions
tresult PLUGIN_API getControllerClassId (TUID classId) SMTG_OVERRIDE
tresult PLUGIN_API getState (IBStream *state) SMTG_OVERRIDE
tresult PLUGIN_API initialize (FUnknown *context) SMTG_OVERRIDE
PluginProcessor ()=default
tresult PLUGIN_API process (ProcessData &data) SMTG_OVERRIDE
Main processing method.
tresult PLUGIN_API setState (IBStream *state) SMTG_OVERRIDE
tresult PLUGIN_API setupProcessing (ProcessSetup &setup) SMTG_OVERRIDE
Sets up internal pipeline processor objects and buffers.
tresult PLUGIN_API terminate () SMTG_OVERRIDE
~PluginProcessor () override=default
Static Public Member Functions
static FUnknown * createInstance (void *)
Private Member Functions
bool getBypassState (const ProcessData &data) const
Helper to safely get the plugin's bypass state.
Private Attributes
ParamValue bypassState = 0.0f
std::shared_ptr< Equalizer > equalizer_
Equalizer being used in the signal processing chain.
std::vector< std::unique_ptr< FFTProcessor > > fft_processors_
FFT processors for each audio channel.
Detailed Description
Main class for the audio processing part of the plugin.
Called by the host. Works with provided samples, outputs them for further actions.
Definition at line 27 of file processor.hpp.
Constructor & Destructor Documentation
PluginProcessor()
PluginProcessor::PluginProcessor () default
~PluginProcessor()
PluginProcessor::~PluginProcessor () override default
Member Function Documentation
createInstance()
static FUnknown * PluginProcessor::createInstance (void *) inline static
Definition at line 33 of file processor.hpp.
{ return static_cast<IAudioProcessor *>(new PluginProcessor()); }
References PluginProcessor().
getBypassState()
bool PluginProcessor::getBypassState (const ProcessData & data) const private
Helper to safely get the plugin's bypass state.
Parameters
data Parameter data
Returns
State boolean
Definition at line 90 of file processor.cpp.
{
    if (!data.inputParameterChanges)
        return bypassState == 1.0f;
    for (int32 i = 0; i < data.inputParameterChanges->getParameterCount(); ++i)
    {
        auto* queue = data.inputParameterChanges->getParameterData(i);
        if (!queue || queue->getParameterId() != kParamBypass)
            continue;
        int32 sampleOffset;
        ParamValue value;
        if(queue->getPoint(queue->getPointCount() - 1, sampleOffset, value) != kResultTrue)
            continue;
        bool newBypassState = value == 1.0f;
        if (!(bypassState == 1.0f) && newBypassState) {
            for (auto& fft : fft_processors_)
                if (fft) fft->reset();
        }
        const_cast<PluginProcessor*>(this)->bypassState = value;
        return newBypassState;
    }
    return bypassState == 1.0f;
}
References bypassState, fft_processors_, and kParamBypass.
getControllerClassId()
tresult PLUGIN_API PluginProcessor::getControllerClassId (TUID classId)
Definition at line 121 of file processor.cpp.
{
    if (!classId)
        return kInvalidArgument;
    // Copy the controller's FUID into cid
    PluginControllerUID.toTUID(classId);
    return kResultOk;
}
References PluginControllerUID().
getState()
tresult PluginProcessor::getState (IBStream * state)
Definition at line 147 of file processor.cpp.
{
    if (!state)
        return kResultFalse;
    IBStreamer streamer(state, kLittleEndian);
    if (!streamer.writeDouble(bypassState))
        return kResultFalse;
    return kResultOk;
}
References bypassState.
initialize()
tresult PLUGIN_API PluginProcessor::initialize (FUnknown * context)
Definition at line 18 of file processor.cpp.
{
    tresult result = AudioEffect::initialize(context);
    if (result != kResultOk) {
        return result;
    }
    addAudioInput(USTRING("Stereo In"), SpeakerArr::kStereo);
    addAudioOutput(USTRING("Stereo Out"), SpeakerArr::kStereo);
    return kResultOk;
}
process()
tresult PLUGIN_API PluginProcessor::process (ProcessData & data)
Main processing method.
Called periodically by the host when the plugin is not bypassing.
Definition at line 51 of file processor.cpp.
{
    if (!(data.numInputs > 0 && data.inputs[0].numChannels > 0))
        return kResultOk;
    bool isBypass = getBypassState(data);
    equalizer_->update_params(data);
    const int32 numSamples = data.numSamples;
    const float sampleRate = this->processSetup.sampleRate;
    const int32 numChannels = std::min(data.inputs[0].numChannels, static_cast<int32>(fft_processors_.size()));
    if (isBypass)
    {
        for (int32 ch = 0; ch < numChannels; ++ch)
        {
            float* input = data.inputs[0].channelBuffers32[ch];
            float* output = data.outputs[0].channelBuffers32[ch];
            if (input && output) {
                std::copy(input, input + numSamples, output);
            }
        }
        return kResultOk;
    }
    for (int32 ch = 0; ch < numChannels; ++ch)
    {
        float* input = data.inputs[0].channelBuffers32[ch];
        float* output = data.outputs[0].channelBuffers32[ch];
        if (input && output) {
            std::copy(input, input + numSamples, output);
            fft_processors_[ch]->process(input, output, sampleRate, numSamples);
        }
    }
    return kResultOk;
}
References equalizer_, fft_processors_, and getBypassState().
setState()
tresult PluginProcessor::setState (IBStream * state)
Definition at line 135 of file processor.cpp.
{
    if (!state)
        return kResultFalse;
    IBStreamer streamer(state, kLittleEndian);
    if (!streamer.readDouble(bypassState))
        return kResultFalse;
    return kResultOk;
}
References bypassState.
setupProcessing()
tresult PLUGIN_API PluginProcessor::setupProcessing (ProcessSetup & setup)
Sets up internal pipeline processor objects and buffers.
Definition at line 28 of file processor.cpp.
{
    tresult result = AudioEffect::setupProcessing(setup);
    if(result != kResultOk)
        return result;
    equalizer_ = std::make_shared<PolynomialEqualizer>();
    if (BusInfo busInfo{}; getBusInfo(kAudio, kInput, 0, busInfo) == kResultOk)
    {
        int32 maxChannels = busInfo.channelCount;
        fft_processors_.resize(maxChannels);
        for (int32 i = 0; i < maxChannels; ++i)
        {
            fft_processors_[i] = std::make_unique<FFTProcessor>();
            fft_processors_[i]->prepare(FFT_SIZE);
            fft_processors_[i]->setEqualizer(equalizer_);
        }
    }
    return kResultOk;
}
References equalizer_, fft_processors_, and FFT_SIZE.
terminate()
tresult PLUGIN_API PluginProcessor::terminate ()
Definition at line 130 of file processor.cpp.
{
    return AudioEffect::terminate();
}
Member Data Documentation
bypassState
ParamValue PluginProcessor::bypassState = 0.0f private
Definition at line 58 of file processor.hpp.
equalizer_
std::shared_ptr<Equalizer> PluginProcessor::equalizer_ private
Equalizer being used in the signal processing chain.
Definition at line 59 of file processor.hpp.
fft_processors_
std::vector<std::unique_ptr<FFTProcessor> > PluginProcessor::fft_processors_ private
FFT processors for each audio channel.
Definition at line 57 of file processor.hpp.
The documentation for this class was generated from the following files:
processor.hpp
processor.cpp